FROM node:20.11-alpine AS build
WORKDIR /app

COPY my-spring-frontend/package*.json ./
RUN npm ci --quiet

COPY my-spring-frontend/ .

RUN npm run build

FROM nginx:1.25-alpine
WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY my-spring-frontend/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist .

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
