input {
  tcp {
    port => 5001
    codec => json
  }
}

filter {

  if [event] == "api_error" {
    mutate { add_tag => ["error"] }
  }

  if [event] == "api_request" {
    mutate { add_tag => ["api"] }
  }

  if [event] == "ticket_purchase_success" {
    mutate { add_tag => ["business"] }
  }

}

output {

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "cinema-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }

}