input {
  tcp {
    port => 5001
    codec => json
  }
}

filter {

  # Разбираем строку message вида:
  # event=api_request path=/api/movies status=200 movie=Dune seatRow=3 seatNumber=7
  kv {
    source => "message"
    field_split => " "
    value_split => "="
  }

  # Приводим типы некоторых полей
  mutate {
    convert => {
      "status" => "integer"
      "seatRow" => "integer"
      "seatNumber" => "integer"
    }
  }

  # Теги для удобной фильтрации в Kibana
  if [event] == "api_error" {
    mutate { add_tag => ["error"] }
  }

  if [event] == "api_request" {
    mutate { add_tag => ["api"] }
  }

  if [event] == "ticket_purchase_success" {
    mutate { add_tag => ["business"] }
  }

}

output {

  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "cinema-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }

}
